'''
# Models.py

from django.db import models

# Create your models here.
class ModelName(models.Model): #id
    field1 = models.CharField(max_length=100)
    field2 = models.CharField(max_length=50, blank=True, null=True, help_text="enter name of field")

    def __str__(self):
        return self.field1
        
        
(venv_name) ➜  project_name git:(main) ✗ python manage.py makemigrations
Migrations for 'appname':
  appname/migrations/0001_initial.py
    + Create model ModelName

# Generated by Django 5.1 on 2024-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.CharField(blank=True, help_text='enter name of field', max_length=50, null=True)),
            ],
        ),
    ]
    
(venv_name) ➜  project_name git:(main) ✗ python manage.py migrate       
Operations to perform:
  Apply all migrations: admin, appname, auth, contenttypes, sessions
Running migrations:
  Applying appname.0001_initial... OK
(venv_name) ➜  project_name git:(main) ✗ 


# Admin.py 
from django.contrib import admin
from .models import *


admin.site.register(ModelName)



'''